### ISSUE TITLE
Enso Firmware Glitch, Shows 3.63

### ISSUE THREAD

**Issue by Gimpy3887** [henkaku/enso#1]
I have Enso installed on my 3.60 PSVita. I was in the process of using my sd2vita adapter when I noticed that the firmware version in settings shows 3.63; strangely, I'm still able to run Vitashell and a GBA Emulator. The Henkaku Settings has disappeared though. I checked my notifications there's none that states a update was installed or even downloaded. I'm wondering how I should go about fixing this glitch. :/

Update: I restarted my Vita, and it's fixed the issue.

**Comment by yifanlu** [comment]
That is firmware spoofing enabled and henkaku settings plugin not being loaded.
