### ISSUE TITLE
Building fails "conflicting types"

### ISSUE THREAD

**Issue by devingDev** [henkaku/enso#10]
Using latest vitasdk.

https://pastebin.com/0cAGA2XL  :

`root@wifi-h:~/VitaProjects/enso/installer# ls res/
bg.png  fat.bin  icon.png  startup.png  template.xml
root@wifi-h:~/VitaProjects/enso/installer# mkdir build && cd build && cmake .. && make
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/vitasdk/bin/arm-vita-eabi-g++
-- Check for working CXX compiler: /usr/local/vitasdk/bin/arm-vita-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/VitaProjects/enso/installer/build
Scanning dependencies of target emmc_helper
[  3%] Building C object CMakeFiles/emmc_helper.dir/src/kernel.c.obj
[  7%] Building C object CMakeFiles/emmc_helper.dir/src/crc32.c.obj
[ 11%] Linking C executable emmc_helper
[ 11%] Built target emmc_helper
Scanning dependencies of target emmc_helper_stubs
[ 15%] Generating imports YAML for emmc_helper
[ 19%] Building stubs emmc_helper_stubs
[ 19%] Built target emmc_helper_stubs
Scanning dependencies of target emmc_helper_user
[ 23%] Building C object CMakeFiles/emmc_helper_user.dir/src/user.c.obj
[ 26%] Linking C executable emmc_helper_user
[ 26%] Built target emmc_helper_user
Scanning dependencies of target emmc_helper_user.suprx
[ 30%] Converting to Sony ELF emmc_helper_user.velf
[ 34%] Creating SELF emmc_helper_user.suprx
[ 34%] Built target emmc_helper_user.suprx
Scanning dependencies of target emmc_helper_user_stubs
[ 38%] Generating imports YAML for emmc_helper_user
[ 42%] Building stubs emmc_helper_user_stubs
[ 42%] Built target emmc_helper_user_stubs
Scanning dependencies of target emmc_helper.skprx
[ 46%] Converting to Sony ELF emmc_helper.velf
[ 50%] Creating SELF emmc_helper.skprx
[ 50%] Built target emmc_helper.skprx
Scanning dependencies of target kernel2
[ 53%] Building C object CMakeFiles/kernel2.dir/src/kernel2.c.obj
[ 57%] Linking C executable kernel2
[ 57%] Built target kernel2
Scanning dependencies of target kernel2.skprx
[ 61%] Converting to Sony ELF kernel2.velf
[ 65%] Creating SELF kernel2.skprx
[ 65%] Built target kernel2.skprx
Scanning dependencies of target enso_installer
[ 69%] Building C object CMakeFiles/enso_installer.dir/src/main.c.obj
/root/VitaProjects/enso/installer/src/main.c:27:5: error: conflicting types for 'sceKernelPowerLock'
 int sceKernelPowerLock(int x);
     ^~~~~~~~~~~~~~~~~~
In file included from /root/VitaProjects/enso/installer/src/main.c:1:0:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:65:5: note: previous declaration of 'sceKernelPowerLock' was here
 int sceKernelPowerLock(SceKernelPowerTickType type);
     ^~~~~~~~~~~~~~~~~~
/root/VitaProjects/enso/installer/src/main.c:28:5: error: conflicting types for 'sceKernelPowerUnlock'
 int sceKernelPowerUnlock(int x);
     ^~~~~~~~~~~~~~~~~~~~
In file included from /root/VitaProjects/enso/installer/src/main.c:1:0:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:74:5: note: previous declaration of 'sceKernelPowerUnlock' was here
 int sceKernelPowerUnlock(SceKernelPowerTickType type);
     ^~~~~~~~~~~~~~~~~~~~
CMakeFiles/enso_installer.dir/build.make:62: die Regel für Ziel „CMakeFiles/enso_installer.dir/src/main.c.obj“ scheiterte
make[2]: *** [CMakeFiles/enso_installer.dir/src/main.c.obj] Fehler 1
CMakeFiles/Makefile2:218: die Regel für Ziel „CMakeFiles/enso_installer.dir/all“ scheiterte
make[1]: *** [CMakeFiles/enso_installer.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2`

**Comment by CelesteBlue-dev** [comment]
@DaveeFTW please merge #14 and close this issue.

**Comment by yifanlu** [comment]
Fixed in the latest commit.
