### ISSUE TITLE
when uninstall ensō...memory card could be disassociated automatically

### ISSUE THREAD

**Issue by developer-sp** [henkaku/enso#11]
I says this because spoof fw3.67, then it need to format the memory card(better option) or update for 3.67(bad way), and this can be sad :( 
Thanks, and congrats for your work.

**Comment by yifanlu** [comment]
It’s actually a henkaku bug that id.dat is updated with spoofed version.

**Comment by yifanlu** [comment]
Someone should fix that instead of a band-aid for the problem.
