### ISSUE TITLE
How to update to V1.1

### ISSUE THREAD

**Issue by masoudr** [henkaku/enso#17]
Hi,
My question might be a little unclear but I need to ask it.
I just forgot to uninstall the old `enso` (V1.0) on my previous firmware (3.60) and manually updated my vita from 3.60 to 3.65. So as you already know if I try to uninstall it, it would brick my vita. So I need to uninstall `enso` and currently, the V1.0 has been installed. Is it safe for me to just remove the old `enso` app and just install the new version and use its uninstaller to safely remove it?
Thanks.

**Comment by yifanlu** [comment]
If you updated to 3.65 it’s already uninstalled. Nothing else is needed.
