### ISSUE TITLE
Installation aborted due to unknown data detected.

### ISSUE THREAD

**Issue by Inf-nite** [henkaku/enso#18]
After modoru down from 3.68. Enso failed to install on both 3.65 and 3.60.

Enso.log https://pastebin.com/TU5Jbke7

**Comment by CelesteBlue-dev** [comment]
reinstall FW 3.60:
- using QCMA
or
- by copying 3.60 PSP2UPDAT.PUP to ux0:data/PSP/UPDATE/
then going to Settings -> System Update -> By storage device

**Comment by xyzz** [comment]
Upload your `ux0:data/blocks.bin`.

**Comment by Inf-nite** [comment]
The problem persisted even after reinstalling FW3.60
[blocks.bin.zip](https://github.com/henkaku/enso/files/2867182/blocks.bin.zip)

**Comment by xyzz** [comment]
Install the latest release from https://github.com/henkaku/enso/releases, then run uninstall from the enso app, reboot, then run install.

**Comment by Inf-nite** [comment]
Uninstalling has cleaned up the issue. Thank you for the help.
