### ISSUE TITLE
Game save/load function not working after standby for more than 12hours

### ISSUE THREAD

**Issue by dizz00** [henkaku/enso#3]
After you let your system standby for long period with some games still running, the save/load function is not working unless you restart the game. The shortest standby for this to happen to me is ~6hrs i guess, but if it's past 12hrs the issue is sure to show up at least for me.

The game i tried:
-digimon cyber sleuth: it won't let you save or load, and will says the save file is corrupted. It is back to normal and the save file is usable after you restart the game.
-project diva f 2nd: the manual and auto-save function won't work until you restart the game.
The games can be played normally except saving/loading save file.

**Comment by yifanlu** [comment]
That's a known problem due to dumpers making improper dumps. We do not support anything piracy/backup related.
